### ISSUE TITLE
Error with close button on window after 'Play again'

### ISSUE THREAD

**Issue by kshivamraj32** [vineetjc/pygame-Search-the-Key#27]

**Comment by vineetjc** [comment]
@kshivamraj32 please check again, we do have an exit option on the main menu. I'm closing this for now, reopen if there's an issue.

**Comment by kshivamraj32** [comment]
Yes

**Comment by vineetjc** [comment]
I'm assigning it to you @kshivamraj32

**Comment by kshivamraj32** [comment]
Implemented the exit function.
I did not find any error with close button on window

**Comment by vineetjc** [comment]
Closing wrt #33

**Comment by ckarthik14** [comment]
There is a small error with the close button. When the 'Play Again' button is clicked after finishing the game once, the close button does not close the window.

**Comment by vineetjc** [comment]
@ckarthik14 I thought so, I was right then.

**Comment by kshivamraj32** [comment]
I do not experience any such error.

**Comment by vineetjc** [comment]
@kshivamraj32 are you sure? I'm talking about the close button on the game window, not the exit button in the game.

**Comment by kshivamraj32** [comment]
Yes, I checked it multiple times. I don't find any issue. 
Please have a look at the following screen recording-
https://drive.google.com/open?id=1VnffVxcG3Hf2UwWWBRxTQ8enecSkdyYq

**Comment by vineetjc** [comment]
Closed wrt #41
