### ISSUE TITLE
Flexibility of number of turns as a setting

### ISSUE THREAD

**Issue by vineetjc** [vineetjc/pygame-Search-the-Key#8]

**Comment by vineetjc** [comment]
@kaushik-ck is assigned this issue

**Comment by kaushik-ck** [comment]
@vineetjc for the number of turns I have given the user to select from a predetermined number of turns (ranging from 4-7). Is this fine or were you expecting something else ?

**Comment by vineetjc** [comment]
@kaushik-ck  Lot of things can be tried:

- I haven't given any specifications, but you can try what you've commented above.
- If it's too 'unfair' on the user then maybe size of grid could be changed accordingly?
- If you're trying to change both the number of turns and size of grid, then maybe you can make 'easy', 'intermediate', 'hard' modes?

This can go many ways, I need opinions.

**Comment by kaushik-ck** [comment]
Oh okay for now I have given the user to select the number of turns (4-7 turns) for the same 5x5 grid. 
I feel the option to select grid size can be separate. I'll make the PR by tomorrow night.

**Comment by vineetjc** [comment]
Closing wrt #30

**Comment by vineetjc** [comment]
#43 enhances.
